title: Flying Behr
email: dylanibehr@gmail.com
description: A photo blog and personal journal.
baseurl: ""
url: "https://flyingbehr.com"
github_username: dylanibehr

# Build settings
theme: minima
plugins:
  - jekyll-feed